### ISSUE TITLE
Chat to Argo CD developers

### ISSUE THREAD

**Issue by alexec** [jmckind/argocd-operator#1]
Hi John,

We'd like to know more about this. Up for a chat?

Alex

See (https://github.com/argoproj/argo-cd/issues/2462)

**Comment by jmckind** [comment]
Hey @alexec, would love to! This was something that I have been playing around with in isolation but would love to figure out if it can be used as a starting point for a fully supported operator. Will also respond on that issue.

**Comment by jmckind** [comment]
Will move the discussion over to https://github.com/argoproj/argo-cd/issues/2462
