### ISSUE TITLE
Improvements to handle TLS, GRPC protocol

### ISSUE THREAD

**Issue by ch-stark** [jmckind/argocd-operator#10]
By default, ArgoCD exposes its API using TLS capabilities, that means that TLS will be terminated by the Argo CD Server, when using OpenShift Router this causes problem for some route types (like edge).
In order to fix that you need to run the Argo CD Server in "insecure" mode, that means Argo CD won't configure TLS on its API, instead the API will be available thru plain http.
The change might be added here:
https://github.com/jmckind/argocd-operator/blob/master/pkg/controller/argocd/deployment.go#L406-L410
The argument you want to add is '--insecure'.
This should be configured only if Argo CD is going to be exposed using an OpenShift Route.
On top of that there are other implications, the connectivity from argocd cli tool to the Argo CD server uses the GRPC protocol, when running ArgoCD behind an OpenShift Route, you need to add '--grpc-web' parameter to argocd cli commands, otherwise it will fail since the HAProxy that we use as Router doesn't support grpc yet (it will be supported with HAProxy 2.0 which will be included in a future OCP).

**Comment by jmckind** [comment]
Working on this in the [tls branch](https://github.com/jmckind/argocd-operator/tree/tls).

**Comment by jmckind** [comment]
@ch-stark I have merged in support for toggling TLS on/off into master. Have a look at https://github.com/jmckind/argocd-operator/blob/master/examples/argocd-tls.yaml for usage.

**Comment by jmckind** [comment]
@ch-stark The TLS issue should be resolved. Please have a look at master when you get some time to see if that is working for you. With regard to the GRPC issue, is that something that the operator can solve? Would creating multiple routes be an option?

**Comment by disposab1e** [comment]
Two routes is an option, this method is used when a Kubernetes ingress controller can't support grpc and https on the same port. See Option 2 here (https://argoproj.github.io/argo-cd/operator-manual/ingress/)

**Comment by jmckind** [comment]
I have pushed a lot of stability updates and a new [release](https://github.com/jmckind/argocd-operator/releases/tag/v0.0.2) that I would like feedback on if you all have some time.

The following two guides are working for me but would like feedback on where the documentation is lacking.

1. [Kubernetes Install](https://github.com/jmckind/argocd-operator/blob/v0.0.2/docs/guides/install-basic.md)
2. [OpenShift Install](https://github.com/jmckind/argocd-operator/blob/v0.0.2/docs/guides/install-openshift.md)

Going back to GRPC, does it work with the flag mentioned and something that can be listed as a workaround? Is this more of an OpenShift/HA Proxt issue or that the resources need to be configured a certain way?

**Comment by disposab1e** [comment]
Good Morning John, will have a look ....

**Comment by disposab1e** [comment]
Checked: Kubernetes Install (install-basic.md) awesome!

**Comment by disposab1e** [comment]
To be honest i'm not a friend of naming the Argo CD deployment objects different. argocd-minimal-server, argocd-insecure-server..... this makes documentation difficult. why not using the same name for all kind of examples?

**Comment by disposab1e** [comment]
Soemtimes it's nice to have a Cleanup of the example.

**Comment by disposab1e** [comment]
Checked: install-olm.md Wow! Learning from the pros! All went smooth! I wonder... you use an CatalogSource and not an OperatorSource so all went fine in Minikube. This is a puzzle peace I searched for :-)

**Comment by disposab1e** [comment]
Typo: usage.md (missing space)

The ArgoCD Server component should be available via a Service.
kubectl get svc -n argocd

**Comment by disposab1e** [comment]
Comming back to GRPC: Tested install-openshift.md

Not working:
`argocd login --insecure --username admin --password xxx argocd-insecure-server-argocd.apps-crc.testing`

Workaround:
argocd login --insecure --grcp-web --username admin --password xxx argocd-insecure-server-argocd.apps-crc.testing

**Comment by disposab1e** [comment]
There is also an discussion [here](https://github.com/argoproj/argo-helm/issues/148).

**Comment by disposab1e** [comment]
I think the best options are:

- The edge termination route from the insecure example 
- and the passthrough route. 

With the passthrough route you don't have to set the --insecure flag and you don't have to set --grpc-web switch for the client.

**Comment by disposab1e** [comment]
Regarding Haproxy... I think this is an OpenShift issue because the HA-PROXY version used in 4.2.2 is:

sh-4.2$ haproxy -v
HA-Proxy version 1.8.17 2019/01/08
Copyright 2000-2019 Willy Tarreau <willy@haproxy.org>

gRPC support in haproxy was [introduced in 1.9.2](https://www.haproxy.com/blog/haproxy-1-9-2-adds-grpc-support/) and [expanded in 2.0](https://www.haproxy.com/blog/haproxy-2-0-and-beyond/)

So the only options are:
- ssl passthrough, so argocd handles the grpc protocol in the server
- edge termination with skipping grcp (--grcp-web) on the client side

**Comment by disposab1e** [comment]
I think it's time to delete:
- install-macos-crc.md 	
- install-macos-minikube.md
This is outdated and you did it better. 

and it's time to delete:
- marketplace/openshift
- helm
This is outdated and you did it better. 

Your docs a clearer so no need for this confusing things! We can document it again.

**Comment by disposab1e** [comment]
One more thing... here is a snippet form the ArgoCD guys to change the default password:

Following commands change the default password to ``Password1!``

```
oc -n argocd patch secret argocd-secret \
-p '{"stringData": {
    "admin.password": "$2a$10$hDj12Tw9xVmvybSahN1Y0.f9DZixxN8oybyA32Uy/eqWklFU4Mo8O",
    "admin.passwordMtime": "'$(date +%FT%T%Z)'"
}}'

kubectl -n argocd patch secret argocd-secret \
-p '{"stringData": {
    "admin.password": "$2a$10$hDj12Tw9xVmvybSahN1Y0.f9DZixxN8oybyA32Uy/eqWklFU4Mo8O",
    "admin.passwordMtime": "'$(date +%FT%T%Z)'"
}}'
```
I personally like this snippet :-)

**Comment by disposab1e** [comment]
One more thing.... I was playing around with argo and operators and cause I'm to stupid (or lazy) to really do it with go :-) ... I finished [my own little operator project](https://github.com/disposab1e/argocd-operator-helm) yesterday. Just a helm based operator based on the argocd helm chart.  I'm aware that your operator will be first choice in the future.. but for me it was important to play a little bit around without disturbing anybody :-) Perhaps it might be a good idea for the future to switch the documentation to Read the Docs. I like the way they handle versioned docs... see [my example](https://argocd-operator-helm.readthedocs.io/en/latest/).

**Comment by disposab1e** [comment]
Here is the logo from argo as svg. Found the original one at: https://github.com/argoproj/argo/blob/master/os-project-logo.svg and resized it a bit... think svg's sacle better than pngs

here from my csv:

```
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+Cjxzdmcgd2lkdGg9IjEwMCUiIGhlaWdodD0iMTAwJSIgdmlld0JveD0iMCAwIDIzIDMwIiB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHhtbDpzcGFjZT0icHJlc2VydmUiIHhtbG5zOnNlcmlmPSJodHRwOi8vd3d3LnNlcmlmLmNvbS8iIHN0eWxlPSJmaWxsLXJ1bGU6ZXZlbm9kZDtjbGlwLXJ1bGU6ZXZlbm9kZDtzdHJva2UtbGluZWpvaW46cm91bmQ7c3Ryb2tlLW1pdGVybGltaXQ6MjsiPgogICAgPGcgdHJhbnNmb3JtPSJtYXRyaXgoMSwwLDAsMSwtOS4yLC03KSI+CiAgICAgICAgPGc+CiAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgPHBhdGggZD0iTTE2LDI3LjdDMTYsMjcuNyAxNS44LDI4LjMgMTUuNSwyOC42QzE1LjMsMjguOCAxNS4xLDI4LjkgMTQuOCwyOC45QzE0LjEsMjkuMSAxMy4zLDI5LjIgMTMuMywyOS4yQzEzLjMsMjkuMiAxNCwyOS4zIDE0LjgsMjkuNEMxNS4xLDI5LjQgMTUuMSwyOS40IDE1LjMsMjkuNUMxNS44LDI5LjUgMTYsMjkuMiAxNiwyOS4yTDE2LDI3LjdaIiBzdHlsZT0iZmlsbDpyZ2IoMjMzLDEwMSw3NSk7ZmlsbC1ydWxlOm5vbnplcm87Ii8+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMjUuMiwyNy43QzI1LjIsMjcuNyAyNS40LDI4LjMgMjUuNywyOC42QzI1LjksMjguOCAyNi4xLDI4LjkgMjYuNCwyOC45QzI3LjEsMjkuMSAyNy45LDI5LjIgMjcuOSwyOS4yQzI3LjksMjkuMiAyNy4yLDI5LjMgMjYuMywyOS40QzI2LDI5LjQgMjYsMjkuNCAyNS44LDI5LjVDMjUuMiwyOS41IDI1LjEsMjkuMiAyNS4xLDI5LjJMMjUuMiwyNy43WiIgc3R5bGU9ImZpbGw6cmdiKDIzMywxMDEsNzUpO2ZpbGwtcnVsZTpub256ZXJvOyIvPgogICAgICAgICAgICA8L2c+CiAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iMjAuNyIgY3k9IjE3LjgiIHI9IjEwLjgiIHN0eWxlPSJmaWxsOnJnYigxODIsMjA3LDIzNCk7Ii8+CiAgICAgICAgICAgICAgICA8Y2lyY2xlIGN4PSIyMC43IiBjeT0iMTcuOCIgcj0iMTAuNCIgc3R5bGU9ImZpbGw6cmdiKDIzMCwyNDUsMjQ4KTsiLz4KICAgICAgICAgICAgICAgIDxjaXJjbGUgY3g9IjIwLjciIGN5PSIxOCIgcj0iOC41IiBzdHlsZT0iZmlsbDpyZ2IoMjA4LDIzMiwyNDApOyIvPgogICAgICAgICAgICAgICAgPGcgaWQ9IkJvZHlfMV8iPgogICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0xNS43LDIyQzE1LjcsMjIgMTYuNCwzMy4zIDE2LjQsMzMuNUMxNi40LDMzLjYgMTYuNSwzMy44IDE2LDM0QzE1LjUsMzQuMiAxMy45LDM0LjYgMTMuOSwzNC42TDE2LjMsMzQuNkMxNy40LDM0LjYgMTcuNCwzMy43IDE3LjQsMzMuNUMxNy40LDMzLjMgMTcuNywyOSAxNy43LDI5QzE3LjcsMjkgMTcuOCwzNC4xIDE3LjgsMzQuM0MxNy44LDM0LjUgMTcuNywzNC44IDE3LDM1QzE2LjUsMzUuMSAxNSwzNS40IDE1LDM1LjRMMTcuMywzNS40QzE4LjcsMzUuNCAxOC43LDM0LjUgMTguNywzNC41TDE5LDMwQzE5LDMwIDE5LjEsMzQuNSAxOS4xLDM1QzE5LjEsMzUuNCAxOC44LDM1LjcgMTcuNywzNS45QzE3LDM2LjEgMTYuMSwzNi4zIDE2LjEsMzYuM0wxOC43LDM2LjNDMjAsMzYuMiAyMC4yLDM1LjMgMjAuMiwzNS4zTDIyLjQsMjQuMUwxNS43LDIyWiIgc3R5bGU9ImZpbGw6cmdiKDIzOCwxMjEsNzUpO2ZpbGwtcnVsZTpub256ZXJvOyIvPgogICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0yNS43LDIyQzI1LjcsMjIgMjUsMzMuMyAyNSwzMy41QzI1LDMzLjYgMjQuOSwzMy44IDI1LjQsMzRDMjUuOSwzNC4yIDI3LjUsMzQuNiAyNy41LDM0LjZMMjUuMSwzNC42QzI0LDM0LjYgMjQsMzMuNyAyNCwzMy41QzI0LDMzLjMgMjMuNywyOSAyMy43LDI5QzIzLjcsMjkgMjMuNiwzNC4xIDIzLjYsMzQuM0MyMy42LDM0LjUgMjMuNywzNC44IDI0LjQsMzVDMjQuOSwzNS4xIDI2LjQsMzUuNCAyNi40LDM1LjRMMjQuMSwzNS40QzIyLjcsMzUuNCAyMi43LDM0LjUgMjIuNywzNC41TDIyLjQsMzBDMjIuNCwzMCAyMi4zLDM0LjUgMjIuMywzNUMyMi4zLDM1LjQgMjIuNiwzNS43IDIzLjcsMzUuOUMyNC40LDM2LjEgMjUuMywzNi4zIDI1LjMsMzYuM0wyMi43LDM2LjNDMjEuNCwzNi4yIDIxLjIsMzUuMyAyMS4yLDM1LjNMMTksMjQuMUwyNS43LDIyWiIgc3R5bGU9ImZpbGw6cmdiKDIzOCwxMjEsNzUpO2ZpbGwtcnVsZTpub256ZXJvOyIvPgogICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0yNS44LDE2LjVDMjUuOCwxOS4zIDIzLjUsMjEuNSAyMC44LDIxLjVDMTguMSwyMS41IDE1LjgsMTkuMiAxNS44LDE2LjVDMTUuOCwxMy44IDE4LjEsMTEuNSAyMC44LDExLjVDMjMuNSwxMS41IDI1LjgsMTMuNyAyNS44LDE2LjVaIiBzdHlsZT0iZmlsbDpyZ2IoMjM4LDEyMSw3NSk7ZmlsbC1ydWxlOm5vbnplcm87Ii8+CiAgICAgICAgICAgICAgICAgICAgPGNsaXBQYXRoIGlkPSJfY2xpcDEiPgogICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMjUuOCwxNi4zTDI1LjIsMzBMMTYuMiwzMEwxNS43LDE2LjMiLz4KICAgICAgICAgICAgICAgICAgICA8L2NsaXBQYXRoPgogICAgICAgICAgICAgICAgICAgIDxnIGNsaXAtcGF0aD0idXJsKCNfY2xpcDEpIj4KICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iMjAuOCIgY3k9IjE5LjIiIHI9IjguOSIgc3R5bGU9ImZpbGw6cmdiKDIzOCwxMjEsNzUpOyIvPgogICAgICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMjUuNSwyMkMyNS41LDIyIDI2LjEsMTYuNyAyNS4zLDE0LjdDMjMuOCwxMS4yIDIwLjMsMTEuNSAyMC4zLDExLjVDMjAuMywxMS41IDIyLjMsMTIuMyAyMi40LDE1LjNDMjIuNSwxNy40IDIyLjQsMjAuNSAyMi40LDIwLjVMMjUuNSwyMloiIHN0eWxlPSJmaWxsOnJnYigyMjcsNzgsNTkpO2ZpbGwtb3BhY2l0eTowLjIyO2ZpbGwtcnVsZTpub256ZXJvOyIvPgogICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICAgICAgPGcgaWQ9IkZhY2VfMV8iPgogICAgICAgICAgICAgICAgICAgIDxjaXJjbGUgY3g9IjE4LjciIGN5PSIxMy44IiByPSIwLjciIHN0eWxlPSJmaWxsOnJnYigyNTEsMjIzLDE5NSk7ZmlsbC1vcGFjaXR5OjAuNTsiLz4KICAgICAgICAgICAgICAgICAgICA8Zz4KICAgICAgICAgICAgICAgICAgICAgICAgPGc+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMjIuNSwyNEMyMi41LDI1LjcgMjEuNywyNi44IDIwLjcsMjYuOEMxOS43LDI2LjggMTguOSwyNS41IDE4LjksMjMuOEMxOC45LDIzLjggMTkuNywyNS40IDIwLjgsMjUuNEMyMS45LDI1LjQgMjIuNSwyNCAyMi41LDI0WiIgc3R5bGU9ImZpbGw6cmdiKDEsMSwxKTtmaWxsLXJ1bGU6bm9uemVybzsiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0yMi41LDI0QzIyLjUsMjUuMSAyMS43LDI1LjcgMjAuNywyNS43QzE5LjcsMjUuNyAxOSwyNC45IDE5LDIzLjlDMTksMjMuOSAxOS44LDI0LjkgMjAuOSwyNC45QzIyLDI0LjkgMjIuNSwyNCAyMi41LDI0WiIgc3R5bGU9ImZpbGw6d2hpdGU7ZmlsbC1ydWxlOm5vbnplcm87Ii8+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgICAgICAgICAgPGc+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Zz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Zz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iMjQuMiIgY3k9IjE5LjMiIHI9IjMuMSIgc3R5bGU9ImZpbGw6cmdiKDIzMywxMDEsNzUpOyIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2lyY2xlIGN4PSIxNy4yIiBjeT0iMTkuMyIgcj0iMy4xIiBzdHlsZT0iZmlsbDpyZ2IoMjMzLDEwMSw3NSk7Ii8+CiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2lyY2xlIGN4PSIyNC4yIiBjeT0iMTkuMyIgcj0iMi40IiBzdHlsZT0iZmlsbDp3aGl0ZTsiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iMTciIGN5PSIxOS4zIiByPSIyLjQiIHN0eWxlPSJmaWxsOndoaXRlOyIvPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjaXJjbGUgY3g9IjE3IiBjeT0iMTkiIHI9IjAuNyIgc3R5bGU9ImZpbGw6cmdiKDEsMSwxKTsiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2lyY2xlIGN4PSIyNC4yIiBjeT0iMTkiIHI9IjAuNyIgc3R5bGU9ImZpbGw6cmdiKDEsMSwxKTsiLz4KICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgICAgICAgICAgPC9nPgogICAgICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik05LjcsMjAuNUM5LjQsMjAuNSA5LjIsMjAuMyA5LjIsMjBMOS4yLDE2QzkuMiwxNS43IDkuNCwxNS41IDkuNywxNS41QzEwLDE1LjUgMTAuMiwxNS43IDEwLjIsMTZMMTAuMiwyMEMxMC4yLDIwLjMgMTAsMjAuNSA5LjcsMjAuNVoiIHN0eWxlPSJmaWxsOnJnYigxODIsMjA3LDIzNCk7ZmlsbC1ydWxlOm5vbnplcm87Ii8+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMzEuNSwyMC41QzMxLjIsMjAuNSAzMSwyMC4zIDMxLDIwTDMxLDE2QzMxLDE1LjcgMzEuMiwxNS41IDMxLjUsMTUuNUMzMS44LDE1LjUgMzIsMTUuNyAzMiwxNkwzMiwyMEMzMiwyMC4zIDMxLjgsMjAuNSAzMS41LDIwLjVaIiBzdHlsZT0iZmlsbDpyZ2IoMTgyLDIwNywyMzQpO2ZpbGwtcnVsZTpub256ZXJvOyIvPgogICAgICAgICAgICAgICAgPGNpcmNsZSBjeD0iMTcuMyIgY3k9IjkuOCIgcj0iMC41IiBzdHlsZT0iZmlsbDp3aGl0ZTsiLz4KICAgICAgICAgICAgICAgIDxwYXRoIGQ9Ik0xMy43LDIzLjNDMTMuNiwyMy4zIDEzLjUsMjMuMyAxMy40LDIzLjJDMTIuMiwyMS43IDExLjYsMTkuOCAxMS42LDE3LjlDMTEuNiwxNi4zIDEyLDE0LjggMTIuOCwxMy40QzEzLjYsMTIuMSAxNC43LDExIDE2LDEwLjJDMTYuMiwxMC4xIDE2LjQsMTAuMiAxNi41LDEwLjNDMTYuNiwxMC41IDE2LjUsMTAuNyAxNi40LDEwLjhDMTMuOSwxMi4yIDEyLjMsMTQuOSAxMi4zLDE3LjhDMTIuMywxOS42IDEyLjksMjEuMyAxNCwyMi43QzE0LjEsMjIuOCAxNC4xLDIzLjEgMTMuOSwyMy4yQzEzLjgsMjMuMyAxMy44LDIzLjMgMTMuNywyMy4zWiIgc3R5bGU9ImZpbGw6d2hpdGU7ZmlsbC1ydWxlOm5vbnplcm87Ii8+CiAgICAgICAgICAgICAgICA8cGF0aCBkPSJNMjUuMiwyOEwyNS4yLDI3LjJDMjMuOCwyOCAyMi4zLDI4LjggMjAuNSwyOC44QzE4LjUsMjguOCAxNy4yLDI3LjkgMTUuOSwyNy4yTDE2LDI4QzE2LDI4IDE3LjUsMjkuNiAyMC42LDI5LjZDMjMuNSwyOS41IDI1LjIsMjggMjUuMiwyOFoiIHN0eWxlPSJmaWxsOnJnYigyMzMsMTAxLDc1KTtmaWxsLW9wYWNpdHk6MC4yNTtmaWxsLXJ1bGU6bm9uemVybzsiLz4KICAgICAgICAgICAgPC9nPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+Cg==
    mediatype: image/svg+xml
```

**Comment by disposab1e** [comment]
What I wonder a little bit... do you really plan to own 

   - kind: Application
      name: applications.argoproj.io

    - kind: AppProject
      name: appprojects.argoproj.io

with the operator? From my point of view these objects don't represent the deployment of Arg CD. They represent the user configuration inside Argo CD.

**Comment by disposab1e** [comment]
One last thing :-) It's great to follow your work and see how to envolve an operator from commit to commit.... awesome work! respect!

**Comment by disposab1e** [comment]
regarding hack/env.sh

`export ARGOCD_OPERATOR_IMAGE=${ARGOCD_OPERATOR_IMAGE:-"${ARGOCD_OPERATOR_REPO}:${ARGOCD_OPERATOR_TAG}"}`

please change to:

`export ARGOCD_OPERATOR_IMAGE=${ARGOCD_OPERATOR_NAME:-"${ARGOCD_OPERATOR_REPO}:${ARGOCD_OPERATOR_TAG}"}`

to get it work...

**Comment by jmckind** [comment]
First, thank you for the feedback, I sincerely appreciate it. I will try to address all of you points in one comment. :)

1. ClusterRoles requiring a namespace. I think that namespace in `deploy/role_binding.yaml` can be removed. I need to test that because OLM handles that for the operator and on my OpenSHift cluster, the ClusterRoleBinding does not have a namespace associated. I will put in a separate issue to investigate that.

2. Naming of the ArgoCD resource in the examples. I see your point there regarding documentation, I figured having them different meant they could be run at the same time for whatever reason but I am fine with the examples all using the same name. We can throw in an PR for that.

3. Clean up commands in documentation. It's funny that you mentiion that, I was thinking it needed the same bust just got lazy at the time. That's an easy PR. :) 

4. CatalogSource vs OperatorSource: There are many ways to get an operator into OLM including stuffing everything into a ConfigMap. For me the CatalogSource pointing to a custom operator catalog registry image works the easiest for my workflow. Having to push a container image everytime you make changes to the CSV could become problematic for some and that is where just using a ConfigMap would probably be a good option, although it has it's issues as well.

Have a look at the [operator bundle docs](https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md) for where the Operator SDK is going as well.

5. Typo with command fixed!

6. GRPC support, I'll admit that I rarely use the argocd client and need to get in the habbit of testing with it more. So am I hearing you correctly that the operator is good? Because it supports the insecure mode for the server and when that is set, the Route uses edge termination. When the server is NOT in insecure mode (the default) the Route is setup in passthrough. That's only on OpenShift of course and I also plan to have the operator create Ingress resurces as an option in the CRD for the non-OpenShift clusters.

7. Delete the guides and helm and marketplace artifacts is fine with me, tried to clean the overall docs up a bit because I noticed it was saying the same thing basically in multiple places. I will put in a PR for that.

8. Change default password is something that I would like to add. I was thinking that the operator could create a secret uniue to the deployment and use that. On OpenShift the operator also sets up Prometheus and Grafana, which need credentials as well. I started on the code to create a Secret for the Grafana credentials, so I can finish that and submit it as a PR.

9. The Helm operator you created is nice, good to see what you have done there. Much the same way, this operator started as a project to learn a bit and just for fun really. I also do like Read the Docs very much and have used it in the past. I have been focused on what needs to be added to the operator but I would love to have somthing like that for the docs for sure.

10. Argo SVG logo, yes I prefer the SVG over PNG for sure due to the size alone. Want to put in a PR for that?

11. The trick as I see it with `Application` and `AppProject` is that they are installed as part of the Argo CD deployment in the install.yaml from the docs. These need to be available when the Argo CD components start up. Therefore, if the operator is responsible for the install, it must provide these resources to the cluster. Another issue is that the  `cluster-admin` Role is needed to install CustomResourceDefinitions in the cluster. The operator does not run with that high level of priveledges. So either the administrator must install them as in the case if the "Basic Install" or OLM does that for us by "owning" them in the CSV. So unfortunately the operator is pinned to a specific version of the Application and AppProject CRDs and must provide them as far as I can tell. I think ultimately it may make the most sense for all of this to live in the main Argo CD repo in the end. :)

12. Fixed the typo in hack/env.sh, thanks!

**Comment by disposab1e** [comment]
Thanks for your feedback! Wow! Will walk through it, comment it and will throw in some PRs.

**Comment by disposab1e** [comment]
add 2.) Ah I understand, perhaps this way it's easier during development. We can keep this in mind and change it if we think it's easier to document.

add 3.) Have everything available from my operator. The next time I test here I check it and will add a PR- 

add 4.) This droves me crazy for days :-) I was reading the operator docs and the first example I saw was with an OperatorSource from the operator-marketplace project. So I installed  operator-marketplace to have a OperatorSource resource. In Kubernetes you than have a marketplace namespace and the OperatorSource was only installable in the marketplace project. But in Kubernetes the markeplace namespace is not a global namespace, so I was not able to install the subscription in the argocd namespace. I tried everything but with no success. 

Having to push a container image is a brilliant idea! Love it... the only downside... the created registry pod has pull IfNotPresent :-( Means I have to manually delete the image from the registry before it gets pushed again when I have changes :-)

add 5.) cool!

add 6.) Yes the operator is perfect!

add 7.) cool! Saw you deleted it already... makes all cleaner!

add 8.) There is also a PR at argo-helm to support this feature. I use this snippet just for development. 

add 9.) thanks.. still learning. All not really complicated but orientation in this quick changing topic is not always easy. I will do the docs in read the Docs. Not hard to start and not so hard to migrate or just use mkdocs.

add 10.) Just added PR

add 11.) I understand! Is there an option to hide these 2 resource form the Web UI, so nobody tries to add Application and AppProject?

add 11.) No thanks for this! Thanks for the hacks! :-)

**Comment by jmckind** [comment]
With regard to (11), that is where I come at it a bit different. I would tend to use the `Application` and `AppProject` CRs and be more "kube-native" and declarative over using the argocd client, if that makes sense.

When you are using the argocd client, you are telling Argo what to do (imperative), however the Kubernetes way is more about expressing what you want it to look like (declarative). It's about what I want, not how to get there.

The way that I look at it is that if someone is already using Argo CD, they are already bought into using manifests stored in a git repo somewhere to describe application infrastructure. The Argo CD Operator takes that one level higher and allows one to describe what they want Argo CD to look like, then can lay down the Applications and AppProjects as well and store all of that in a repo.

**Comment by disposab1e** [comment]
I totally understand what you mean! And yes this makes sense, and yes it was charming to see these resources coming up in Kubernetes when I added a Application/AppProject via the cli. 

Than I was thinking further... what might happen when I'm 'responsible' for these resources?

I think this will be a discussion with many operators... where is the border of kubernetes native application and just the application. When the operator gives the possibilities to crud those resources the operator has to watch for the results/status of failures, constraints or whatever. And than the operaore has to report this to the user. So typically the application and the kubernetes application share the same responsibilities and perhaps implement this in a completely different way. I love your idea of thinking about this... but not sure at this moment what are the consequences.

**Comment by disposab1e** [comment]
But... no risk no fun! :-)

**Comment by disposab1e** [comment]
fyi: https://github.com/disposab1e/argocd-operator-helm with Argo CD 1.3.0 small changes .. I think you migrate the operator in minutes... good night and good luck! :-)

**Comment by jmckind** [comment]
Cheers!
