### ISSUE TITLE
A good starting point for the ArgoCD crd structs?

### ISSUE THREAD

**Issue by disposab1e** [jmckind/argocd-operator#33]
The guys from the argo-cd helm chart did a great job to give the [configuration values a new and more clear structure](https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd).

Perhaps a good starting point for the ArgoCD crd structs?

**Comment by jmckind** [comment]
I like all of that! However, I am cautious to add a lot of configuration options all at once. For one testing all of them is harder and two, how many of those are actually used in the majority of cases? I am curious how much of those options are really used most deployments. Do you have any sense of that? I am not opposed to adding all of that stuff if it's truly needed.

**Comment by disposab1e** [comment]
I totally prefer the way you do it! It makes no sense to add all the options at once. I can see from the Slack channel and some discussions of issues that a lot options are used, even some of them I thought nobody will ever need. So in the long run I think most of them will be used. Perhaps the ArgoCD guys will have a better overview whats really needed in the end.

But anyway... it's better to grab one by one when you implement it.

The differences from your ArgoCD crd structure and the restructured options from the Helm chart are:

Ingress
-------
```
Helm Chart structure:

server.certificate.additionalHosts | Certificate manager additional hosts | [] |  
server.certificate.domain | Certificate manager domain | "argocd.example.com" |  
server.certificate.enabled | Enables a certificate manager certificate. | false |  
server.certificate.issuer | Certificate manager issuer | {}
server.ingress.annotations | Additional ingress annotations | {} |  
server.ingress.enabled | Enable an ingress resource for the server | false |  
server.ingress.hosts | List of ingress hosts | [] |  
server.ingress.labels | Additional ingress labels. | {} |  
server.ingress.tls | Ingress TLS configuration. | [] |  
server.route.enabled | Enable a OpenShift route for the server | false |  
server.route.hostname | Hostname of OpenShift route
```
```
CRD structure

type ArgoCDSpec struct {
.....
	// Ingress defines the Ingress options for ArgoCD.
	Ingress ArgoCDIngressSpec `json:"ingress,omitempty"`

	// TLS defines the TLS options for ArgoCD.
	TLS ArgoCDTLSSpec `json:"tls,omitempty"`
.....
}
```
To go with the structure from the Helm Chart I would propose moving these options to:
```
type ArgoCDServerSpec struct {
......
	// Ingress defines the Ingress options for ArgoCD.
	Ingress ArgoCDIngressSpec `json:"ingress,omitempty"`

	// TLS defines the TLS options for ArgoCD.
	TLS ArgoCDTLSSpec `json:"tls,omitempty"`
......
}
```

**Comment by jmckind** [comment]
Good catch on moving those properties. This is something that I would like to do before releasing v0.0.3

**Comment by jmckind** [comment]
The ArgoCDIngressSpec was put on the top level ArgoCDSpec as global options that would apply to more than just the server component. For example, both Prometheus and Grafana are exposed via ingress when enabled. The question that I have though is would you want finer control over that? For example, would someone want to only expose the server and grafana via Ingress and not Prometheus?

**Comment by jmckind** [comment]
Moving everything over here:

https://github.com/argoproj-labs/argocd-operator/issues
