### ISSUE TITLE
Proposal to implement CircleCI

### ISSUE THREAD

**Issue by disposab1e** [jmckind/argocd-operator#36]
I have started to use CircleCI in my project. In the moment the checks are very simple, just build the operator, verify and build the bundle.

Example [Pull Request](https://github.com/disposab1e/argocd-operator-helm/pull/5) check
[Check Details](https://github.com/disposab1e/argocd-operator-helm/pull/5/checks?check_run_id=310118845)
[What's implemented so far?](https://github.com/disposab1e/argocd-operator-helm/blob/master/.circleci/config.yml)

I think this can do much more in the future! I think a good thing to implement.

**Comment by jmckind** [comment]
Moving everything over here:

https://github.com/argoproj-labs/argocd-operator/issues
